name: sign-recognition-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas>=1.4.0  # Updated to support Python 3.10
  - ffmpeg         # Añadido para soporte multimedia con yt-dlp
  - yt-dlp         # Sustituye a pytube para descargas de vídeo

  - pip:
      - fastdtw==0.3.4
      - mediapipe>=0.10.5  # Updated to available version
      - opencv-contrib-python>=4.5.4.60  # More flexible version
      - tqdm==4.66.4  # tdqm → tqdm
      - customtkinter
